qcm/qcm/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
    path('',include('authentication.urls')),
    
    
]
handler404='authentication.views.error_404_view'

qcm/app1/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Domain(models.Model):
    name=models.CharField(max_length=50)
    description=models.TextField()
    def __str__(self):
        return self.name



# category Model
class Category(models.Model):
    domain = models.ForeignKey(Domain, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    description = models.TextField()
    def __str__(self):
        return self.name 

    class Meta:
        verbose_name_plural="Categories"


# Subcategory Model
class Subcategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural='Subcategories'

# Question Model
class Question(models.Model):
    domain = models.ForeignKey(Domain, on_delete=models.CASCADE,null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE, null=True, blank=True)
    question = models.TextField()
    answer_1 = models.CharField(max_length=255)
    answer_2 = models.CharField(max_length=255)
    answer_3 = models.CharField(max_length=255)
    answer_4 = models.CharField(max_length=255)
    explanation= models.TextField(blank=True,null=True)
    
    def __str__(self):
        return self.question
        

    # Retrive option from a specific Question Model  
    def get_options(self):
        return [(1, self.answer_1), (2, self.answer_2), (3, self.answer_3), (4, self.answer_4)]
    
    # Retrive correct answer 
    def get_correct_answer(self, question_id):
        correct_answer = CorrectAnswer.objects.get(question=question_id).answer
        if correct_answer == 1:
            return self.answer_1
        elif correct_answer == 2:
            return self.answer_2
        elif correct_answer == 3:
            return self.answer_3
        else:
            return self.answer_4
    

    
    """
 
    def get_answer_display(self):
        return getattr(self, 'answer_' + str(self.correctanswer_set.all().first().answer))

    def get_correct_answer(self, question_id):
        correct_answer = CorrectAnswer.objects.get(question=question_id)
        return correct_answer.get_answer_1_display()
    """


class CorrectAnswer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.IntegerField()

    def __str__(self):
        return str(self.answer) +": "+self.question.get_options()[self.answer-1][1]



class Score(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.PositiveIntegerField()
    timestamp = models.DateTimeField(auto_now_add=True)
    domain = models.ForeignKey(Domain, on_delete=models.CASCADE,null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE, null=True, blank=True)


class Feedback(models.Model):
    RATING_CHOICES = [
        (1, 'Very dissatisfied'),
        (2, 'Somewhat dissatisfied'),
        (3, 'Neither satisfied nor dissatisfied'),
        (4, 'Somewhat satisfied'),
        (5, 'Very satisfied'),
    ]
    rating = models.IntegerField(choices=RATING_CHOICES)
    reasons = models.TextField()
    submitted_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Feedback #{self.id}"

qcm/templates/about.html
{% block content %}

<div class="bg-light">
    <div class="container py-5">
      <div class="row h-100 align-items-center py-5">
        <div class="col-lg-6">
          <h1 class="display-4">About Our Quiz Site        </h1>
          <p class="lead text-muted mb-0">Our website is a quiz platform that allows users to test their knowledge and compete against others. With a variety of difficulty levels and timed options, users can customize their quizzing experience to their liking. The platform also features multiple rounds and various opponent options, making it a dynamic and engaging experience for users. Whether users are looking to challenge themselves, compete against friends, or just have fun, our quiz website provides a comprehensive and entertaining platform for all.</p>
         
        </div>
        <div class="col-lg-6 d-none d-lg-block"><img src="https://bootstrapious.com/i/snippets/sn-about/illus.png" alt="" class="img-fluid"></div>
      </div>
    </div>
  </div>

  <style>
    .social-link {
  width: 30px;
  height: 30px;
  border: 1px solid #ddd;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #666;
  border-radius: 50%;
  transition: all 0.3s;
  font-size: 0.9rem;
}

.social-link:hover,
.social-link:focus {
  background: #ddd;
  text-decoration: none;
  color: #555;
}
  </style>

  {% endblock%}

qcm/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
          <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
          <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
        
          <title>Quiz Game</title>
</head>
<body>
    {% include "navbar.html"%}
    {% block content %}
    {% endblock %}
    


    
</body>
</html>

qcm/templates/cardlog.html
<div>
    <div class="header">
      <h1>Quiz your way to the top</h1>
      <h1><!--Powered by Technology--> Choose To Play</h1>
      <p>Our website offers a vast collection of questions and answers covering a wide range of topics</p>
    </div>

    <div class="row1-container">
      
          <div class="box box-down cyan">
            <h2>Network Security</h2>
            <p>Network security is the practice of protecting a computer network from unauthorized access, misuse, and disruption.</p>
            <img src="https://assets.codepen.io/2301174/icon-supervisor.svg" alt="">
          </div>

          <div class="box red">
            <h2>Web Development</h2>
            <p>
              Web development is the process of creating and maintaining websites, typically involving tasks such as coding, content creation, and design.   
            </p>     
            <img src="https://assets.codepen.io/2301174/icon-team-builder.svg" alt="">
          </div>

          <div class="box box-down blue">
            <h2>Cryptography</h2>
            <p>Cryptography is the practice of securing communication through the use of codes and ciphers.
          </p>
            <img src="https://assets.codepen.io/2301174/icon-calculator.svg" alt="">
          </div>

    </div>

    <div class="row2-container">
            <div class="box orange">
              <h2>AI</h2>
              <p>AI is the simulation of human intelligence processes by computer systems.
            </p>
              <img src="https://assets.codepen.io/2301174/icon-karma.svg" alt="">
            </div>
    </div>
</div>

<style>
   
    
      
 

    .warning-box{
    display:none;
    position:absolute;
    opacity: 0;
    bottom: 0;
    top: 0;
    left: 0;
    right: 0;
    text-align: center;
    z-index: 2;
    animation-name: register-notify;
    animation-delay: 500ms;
    animation-timing-function: cubic-bezier(0.4, 0, 0.56, 1.38);
    animation-duration: 2700ms;
  }
  @keyframes register-notify{
    0%{
      top: -100px;
    }
    40%{
      opacity: 1;
      top: 0;
    }
    60%{
      opacity:1;
    }
    99%{
      opacity:0;
      top:200px;
    }
    100%{
      //display: none;
    }
  }
  


#card {
  position: relative;
  width: 320px;
  display: block;
  margin: 40px auto;
  text-align: center;
  font-family: 'Source Sans Pro', sans-serif;
}

#upper-side {
  padding: 2em;
  background-color: #8BC34A;
  display: block;
  color: #fff;
  border-top-right-radius: 8px;
  border-top-left-radius: 8px;
}

#checkmark {
  font-weight: lighter;
  fill: #fff;
  margin: -3.5em auto auto 20px;
}

#status {
  font-weight: lighter;
  text-transform: uppercase;
  letter-spacing: 2px;
  font-size: 1em;
  margin-top: -.2em;
  margin-bottom: 0;
}

#lower-side {
  padding: 2em 2em 5em 2em;
  background: #fff;
  display: block;
  border-bottom-right-radius: 8px;
  border-bottom-left-radius: 8px;
}

#message {
  margin-top: -.5em;
  color: #757575;
  letter-spacing: 1px;
}

#contBtn {
  position: relative;
  top: 1.5em;
  text-decoration: none;
  background: #8bc34a;
  color: #fff;
  margin: auto;
  padding: .8em 3em;
  -webkit-box-shadow: 0px 15px 30px rgba(50, 50, 50, 0.21);
  -moz-box-shadow: 0px 15px 30px rgba(50, 50, 50, 0.21);
  box-shadow: 0px 15px 30px rgba(50, 50, 50, 0.21);
  border-radius: 25px;
  -webkit-transition: all .4s ease;
		-moz-transition: all .4s ease;
		-o-transition: all .4s ease;
		transition: all .4s ease;
}

#contBtn:hover {
  -webkit-box-shadow: 0px 15px 30px rgba(50, 50, 50, 0.41);
  -moz-box-shadow: 0px 15px 30px rgba(50, 50, 50, 0.41);
  box-shadow: 0px 15px 30px rgba(50, 50, 50, 0.41);
  -webkit-transition: all .4s ease;
		-moz-transition: all .4s ease;
		-o-transition: all .4s ease;
		transition: all .4s ease;
}

    :root {
    --red: hsl(0, 78%, 62%);
    --cyan: hsl(180, 62%, 55%);
    --orange: hsl(34, 97%, 64%);
    --blue: hsl(212, 86%, 64%);
    --varyDarkBlue: hsl(234, 12%, 34%);
    --grayishBlue: hsl(229, 6%, 66%);
    --veryLightGray: hsl(0, 0%, 98%);
    --weight1: 200;
    --weight2: 400;
    --weight3: 600;
}

body {
    font-size: 15px;
    font-family: 'Poppins', sans-serif;
    background-color: var(--veryLightGray);
}

.attribution { 
    font-size: 11px; text-align: center; 
}
.attribution a { 
    color: hsl(228, 45%, 44%); 
}

h1:first-of-type {
    font-weight: var(--weight1);
    color: var(--varyDarkBlue);

}

h1:last-of-type {
    color: var(--varyDarkBlue);
}

@media (max-width: 400px) {
    h1 {
        font-size: 1.5rem;
    }
}

.header {
    text-align: center;
    line-height: 0.8;
    margin-bottom: 50px;
    margin-top: 100px;
}

.header p {
    margin: 0 auto;
    line-height: 2;
    color: var(--grayishBlue);
}


.box p {
    color: var(--grayishBlue);
}

.box {
    border-radius: 5px;
    box-shadow: 0px 30px 40px -20px var(--grayishBlue);
    padding: 30px;
    margin: 20px;  
}

img {
    float: right;
}

@media (max-width: 450px) {
    .box {
        height: 200px;
    }
}

@media (max-width: 950px) and (min-width: 450px) {
    .box {
        text-align: center;
        height: 180px;
    }
}

.cyan {
    border-top: 3px solid var(--cyan);
}
.red {
    border-top: 3px solid var(--red);
}
.blue {
    border-top: 3px solid var(--blue);
}
.orange {
    border-top: 3px solid var(--orange);
}

h2 {
    color: var(--varyDarkBlue);
    font-weight: var(--weight3);
}


@media (min-width: 950px) {
    .row1-container {
        display: flex;
        justify-content: center;
        align-items: center;
    }
    
    .row2-container {
        display: flex;
        justify-content: center;
        align-items: center;
    }
    .box-down {
        position: relative;
        top: 150px;
    }
    .box {
        width: 20%;
     
    }
    .header p {
        width: 30%;
    }
    
}
</style>

qcm/templates/cardnotlog.html
<div class="c container">
  <h1>Test Your Wits with a Quiz Adventure - Choose To Play!</h1>

  <div class="r row">

    <div class="service">
      <a class="href" href="/login">
            <i class="fas fa-flask"></i> 
            <h2>Science</h2>
            <p>
              Explore the Mysteries of the Natural World and Satisfy Your Curiosity - Choose Science Today!
            </p>
          </a>
          </div>
    
          <div class="service">
            <a class="href" href="/login">
            <i class="fas fa-gamepad"></i> 
            <h2>Game Development</h2>
            <p>
              Enter the Exciting World of Game Development and Unleash Your Creativity - Choose to Play Now!        </p>
            </p>
          </a>
          </div>

          <div class="service">
            <a class="href" href="/login">
            <i class="fas fa-laptop-code"></i> 
            <h2>Software Development</h2>
            <p>
              Transform Your Ideas into Reality with Cutting-Edge Software Development - Choose to Explore Now!
            </p>
          </a>
          </div>

          <div class="service">
            <a  class="href" href="/login">
            <i class="fas fa-mobile-alt"></i>
            <h2>App Development</h2>
            <p>
              Unlock Your Full Potential in the Dynamic World of Web Development - Choose to Learn and Grow Now!
            </p>
          </a>
          </div>
    
      <div class="service">
            <a class="href" href="/login">
            <i class="fas fa-calculator"></i> 
            <h2>Math</h2>
            <p>
              Transform Your Ideas into Reality with Cutting-Edge Software Development - Choose to Explore Now!      
            </p>
          </a>
          </div>
    
    
      <div class="service">
            <a class="href" href="/login">
            <i class="fas fa-network-wired"></i>
            <h2>Networking</h2>
            <p>
              Connect the World and Power Up Your Career with Networking - Choose to Learn and Grow Now!
            </p>
          </a>
          </div>

  </div>

  
</div>
  
  <style>

    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap');
    .href {
  text-decoration: none;
  color: var(--bs-secondary-color)!important;
}
  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: 'Poppins', sans-serif;
  }
  
  .c {
    width: 100%;
    height: 100%;
    padding: 0px 8%;
  }
  
  .container h1 {
    text-align: center;
    padding-top: 10%;
    margin-bottom: 60px;
    font-weight: 600;
    position: relative;
  }
  
  .container h1::after {
    content: '';
    background: #303ef7;
    width: 100px;
    height: 5px;
    position: absolute;
    bottom: -5px;
    left: 50%;
    transform: translateX(-50%);
  }
  
  .r {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    grid-gap: 30px;
  }
  
  .service {
    text-align: center;
    padding: 25px 10px;
    border-radius: 5px;
    font-size: 14px;
    cursor: pointer;
    background: transparent;
    transition: transform 0.5s, background 0.5s;
  }
  
  .service i {
    font-size: 40px;
    margin-bottom: 10px;
    color: #303ef7;
  }
  
  .service h2 {
    font-weight: 600;
    margin-bottom: 8px;
  }
  
  .service:hover {
    background: #303ef7;
    color: #fff;
    transform: scale(1.05);
  }
  
  .service:hover i {
    color: #fff;
  }
  </style>

qcm/templates/configure_quizz.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<style>

    .form-container {
        background-color: rgba(0, 0, 0, 0.5);
        padding: 50px;
        border-radius: 10px;
        width: 50%;
        margin: auto;
        margin-top:10%;
        box-shadow: 0px 0px 10px 5px #ccc;
    }
    
    .form-group {
        display: flex;
        align-items: center;
        margin-bottom: 20px;
    }
    
    .form-group label {
        width: 30%;
        font-size: 1.2em;
        color: white;
    }
    
    .form-group .form-control {
        width: 60%;
        height: 40px;
        font-size: 1.2em;
        padding-left: 10px;
        border-radius: 5px;
        border: none;
        box-shadow: inset 0px 0px 5px #ccc;
    }
    
    .form-group .form-control::placeholder {
        color: white;
    }
    
    .form-group .fa {
        margin-right: 10px;
        font-size: 1.5em;
        color: white;
    }
    
    input[type="submit"] {
        background-color: #5cb85c;
        color: white;
        border: none;
        border-radius: 5px;
        height: 40px;
        width: 100px;
        margin-right: 20px;
        font-size: 1.2em;
        cursor: pointer;
    }
    
    a.btn-secondary {
        background-color: #8a8a8a;
        color: white;
        border: none;
        border-radius: 5px;
        height: 40px;
        width: 100px;
        font-size: 1.2em;
        cursor: pointer;
        text-align: center;
        text-decoration: none;
    }
    
    </style>
<div class="form-container">
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <i class="fa fa-sliders-h"></i>
            <label for="difficulty"><i class="fa fa-bullseye"></i> Difficulty</label>
            <select name="difficulty" id="difficulty" class="form-control">
                {% for diff in difficulty %}
                <option value="{{ diff }}">{{ diff }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <i class="fa fa-stopwatch"></i>
            <label for="timer"><i class="fa fa-clock-o"></i>Timer</label>
            <input type="number" name="timer" value="{{timer}}" class="form-control">
        </div>
        <div class="form-group">
            <i class="fa fa-user-alt"></i>
            <label for="opponent"><i class="fa fa-user"></i> Opponent</label>
            <select name="opponent" id="opponent" class="form-control">
                {% for opp in opponent %}
                <option value="{{opp}}" >{{ opp }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <i class="fa fa-layer-group"></i>
            <label for="round"> <i class="fa fa-history"></i>  Round</label>
            <select name="round" class="form-control">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
            </select>
        </div>

    <div class="form-group">
        <input type="submit"value="Set" class="btn btn-primary">
        <input type="text" hidden name="quiz-id" value="">
        <a href="/home" class="btn btn-secondary">Go Back</a>
        </div>
        
        </div>
        </form>
        </div>

qcm/templates/index.html
{% include 'base.html' %}
  

{% block content %}
{% if messages %}
    <br>
    <ul class="messages">
    
        {% for message in messages %}
            {% if message.tags == "success" %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ message }} </strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

                </div>
            {% endif %}
        {% endfor %}
    </ul>

{% endif %}


<style>
    .btn-close {
  font-size: 1rem;
  line-height: 1;
}

</style>

{% if user.is_authenticated %}  
{% include "cardlog.html" %}


{% else %}




{% include "cardnotlog.html" %}
<br><br><br>




{% include "about.html" %}

{% endif %}


 

{% endblock %}
{% include "footer.html"%}

qcm/templates/navbar.html
       <!--NavBar-->
<nav class="navbar navbar-expand-lg  navbar-dark bg-dark">

          <div class="container-fluid">   
                 
              <a class="navbar-brand" href="{% url 'home' %}">Home</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              {% if user.is_authenticated %}  
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                  {% for domain in domains %}
                    {% if domain.category_set.all %}
                  <li class="nav-item dropdown">

                    <a class="nav-link dropdown-toggle"  href="#" data-bs-auto-close="outside" role="button" id="{{ domain.id }}_dropdown"data-bs-toggle="dropdown" aria-expanded="false">{{ domain.name }}</a>
                    
                    
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="{{ domain.id }}_dropdown">
                      {% for category in domain.category_set.all %}
                        {% if category.subcategory_set.all %}
                          <li class="nav-item dropend">
                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown"  href="#">{{ category.name }}</a>
                            <ul class="dropdown-menu dropdown-menu-dark">
                              {% for subcategory in category.subcategory_set.all %}
                              
                              <li>
                                <a type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#sy__{{subcategory.id}}">
                                    {{subcategory.name}}
                                </a>
                                  
                              </li>

                                {% endfor %}
                            </ul>
      
                          </li>
                        {% else %}
                          <li><a class="dropdown-item" href="{% url 'show_questions_by_category' category.id %}">{{ category.name }}</a></li>
                        {% endif %}
                      {% endfor %}
                    </ul>
                  </li>
                {% else %}

                <li class="nav-item">
                  <!--here the modal you create it {% url 'show_questions_by_domain' domain.id %} -->
                  <a class="nav-link" data-bs-toggle="modal" data-bs-target="#{{domain.id}}" href="">{{ domain.name }}</a>
                
                          <!-- Modal -->
                          {% load static %}

                              <div class="modal fade" id="{{domain.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                  <div class="modal-content">
                                    <div class="modal-header">
                                      <h1 class="modal-title fs-5" id="exampleModalLabel"><b>{{domain.name}} Knowledge Quiz </b></h1>
                                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                      <img src="{% static 'app1/images/' %}{{domain.name}}.png" alt="{{domain.name}}" />
                                      <p>
                                        {{ domain.description }} 
                                      </p>
                                    </div>
                                    <div class="modal-footer">
                                      <a type="button" href="{% url 'show_questions_by_domain' domain.id %}" class="btn btn-secondary">
                                        
                                        <i class="fas fa-play"></i> Start Quiz
                                      </a>
                                      <a href ="{% url 'configure' %}"type="button" class="btn btn-primary">
                                        <i class="fas fa-cog"></i>
                                        Configure Quizz
                                      </a>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              
                </li>
                
                  
                {% endif %}
                {% endfor %}
              

            
              <li class="nav-item active">
                <a class="nav-link" href="/leaderboard">
                  <i class="fa fa-trophy"></i> Leaderboard
                </a>
              </li>          
          </ul>


          <ul class="navbar-nav ms-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/profile">
                <i class="fa fa-user"></i> Profile 
              </a>
            </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="/configure">
                      <i class="fa fa-cog"></i> Configure Quizz 
                    </a>
                  </li>

                
                      <li class="nav-item">
                        <a class="nav-link" href="/signout">
                          <i class="fa fa-sign-out-alt"></i> Signout
                        </a>
                      </li>

                      {% if user.is_authenticated and user.is_superuser%}
                      <li class="nav-item">
                        <a class="nav-link" href="/admin">
                          <i class="fas fa-user-cog"></i> Admin
                        </a>
                      </li>
                        {% endif %}
          </ul>
      
    

              {% else %}  


              <div class="collapse navbar-collapse" id="navbarSupportedContent">
            
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link" href="#">
                      <i class="fa fa-info-circle"></i> About Us
                    </a>
                  </li>

                </ul>

          <ul class="navbar-nav ms-auto">
                  <li class="nav-item active ">
                    <a class="nav-link" href="/login">
                      <i class="fa fa-sign-in-alt"></i> Login 
                    </a>
                  </li>
                  
                  <li class="nav-item">
                    <a class="nav-link" href="/signup">
                    <i class="fa fa-user-plus"></i> Signup
                  </a>
                </li>
          </ul>
                  
                {% endif %}

      
    </div>     
  </div>     
</nav>

<!--end NavBar-->
      
            {% for subcategorie in subcategories %}
                         <!-- Modal -->
                         <div class="modal fade" id="sy__{{subcategorie.id}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                          <div class="modal-dialog">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h1 class="modal-title fs-5" id="staticBackdropLabel">                            <b>{{subcategorie.name}} Knowledge Quiz </b>                      </h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                              </div>
                              <div class="modal-body">
                                
                                
                                  <img src="{% static 'app1/images/' %}{{subcategorie.name}}.png" alt="{{subcategorie.name}}" />
                                  <p>
                                    {{subcategorie.description}}
                                  </p>

                              </div>
                              <div class="modal-footer">
                                <a type="button" href="{% url 'show_questions_by_subcategory' subcategorie.id %}" class="btn btn-secondary" >
                                  <i class="fas fa-play"></i> Start Quiz
                                  </a>
                                <a href ="{% url 'configure' %}"type="button" class="btn btn-primary">
                                  <i class="fas fa-cog"></i>
                                  Configure Quizz
                                </a>
                              </div>
                            </div>
                          </div>
                        </div>
            {% endfor %} 
                        

<style>
  .modal-header {
  background-color: #f5f5f5;
  padding: 15px;
  border-bottom: 1px solid #ddd;
}
.modal-open .modal {
    backdrop-filter: blur(10px);
  }
  


.modal-title {
  font-size: 20px;
  color: #333;
}

.btn-close {
  float: right;
  font-size: 40px;
  color: #333;
  opacity: 0.5;
}

.modal-dialog {
  max-width: 600px;
}
.modal-open .modal {
    backdrop-filter: blur(10px);
  }
  .modal-body img {
    width: 100%;
  height: 200px; /* set fixed height here */
  object-fit: contain;
  padding-bottom: 20px;
}

.card-image {
  width: 100%;
  height: 200px; /* set fixed height here */
  object-fit: contain;
}
    
    
    
    
    </style>     









    